#pragma once
// Grid maze. Generated by an iterative recursive-backtracker (produces a
// perfect maze: every walkable cell reachable from every other) followed by
// optional braiding that opens extra corridors (removing walls can never
// disconnect the maze). The outer border is always wall.

#include "utility/rng.h"

#include <cstdint>
#include <vector>

namespace sir {

class Maze {
 public:
  Maze(int width, int height);

  // Full (re)generation. Throws std::runtime_error on invalid dimensions.
  void generate(Rng& rng, double braid_probability);

  int width() const { return w_; }
  int height() const { return h_; }
  int cellCount() const { return w_ * h_; }

  bool inBounds(int x, int y) const;
  bool isWall(int x, int y) const;     // true = blocked
  bool isWalkable(int x, int y) const; // in bounds and not a wall

  // BFS reachability (used only for maze validation and tests, never for
  // controlling the rat). Returns the number of walkable cells reached from
  // (sx, sy).
  int reachableCount(int sx, int sy) const;

  // Test/diagnostic helpers.
  void setWallForTests(int x, int y, bool wall);
  const std::vector<uint8_t>& cells() const { return cells_; }

 private:
  void resetAllWalls();
  void carveFrom(int x, int y, Rng& rng);  // iterative backtracker

  int w_;
  int h_;
  std::vector<uint8_t> cells_;  // 1 = wall, 0 = walkable
};

}  // namespace sir
